# -*- coding: utf-8 -*-
"""azka zahid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7QoI0i-Wyn8EF6IpWCE98Fxj322oN2f
"""

name = "Azkazahid "
print (len(name))

name = "Azkazahid "
print(name[0:4])

paragraph="""Paragraphs are the building blocks of papers. Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph."""
print(paragraph.find("blocks"))

paragraph="""Paragraphs are the building blocks of papers. Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph."""
print(paragraph)

text = "I love python"
New_text= text.replace ("python","java")
print(New_text)

text="hello world"
print(text.strip())
print(text.lstrip())
print(text.rstrip())